spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/engine_test?&useSSL=false&serverTimezone=UTC
    username: postgres
    password: newuserR-1
  liquibase:
    change-log: classpath:databaseChangeLog.xml
  jpa:
    properties:
      hibernate:
        spring.jpa.hibernate.ddl-auto: create

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 664-44-55
  email: ruslan@mail.ru
  copyright: Ruslan Saberov
  copyrightFrom: 2005


