spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eng_test?&useSSL=false&serverTimezone=UTC
    username: postgres
    password: newuserR-1
    initialization-mode: always
  liquibase:
    change-log: classpath:db.changelog/databaseChangeLog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 664-44-55
  email: ruslan@mail.ru
  copyright: Ruslan Saberov
  copyrightFrom: 2005

