spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/engine?&useSSL=false&serverTimezone=UTC
    username: postgres
    password: newuserR-1
  jpa:
    properties:
      hibernate:
        spring.jpa.hibernate.ddl-auto: create


